### ISSUE TITLE
Using example in Readme fails with 'NoneType' object has no attribute 'total_seconds'.

### ISSUE THREAD

**Issue by mmzx** [erdewit/ib_insync#537]
When doing the conversion to pandas's dataframe `df = util.df(bars)` as shown in the readme file, I experience the below error, using
 - pandas 1.5.2
 - python 3.8.10
.

Could the respective line be updated in the readme?

```
Traceback (most recent call last):
  File "pandas/_libs/tslibs/tzconversion.pyx", line 85, in pandas._libs.tslibs.tzconversion.Localizer.__cinit__
  File "pandas/_libs/tslibs/timezones.pyx", line 306, in pandas._libs.tslibs.timezones.get_dst_info
AttributeError: 'NoneType' object has no attribute 'total_seconds'
Exception ignored in: 'pandas._libs.tslibs.conversion._localize_tso'
Traceback (most recent call last):
  File "pandas/_libs/tslibs/tzconversion.pyx", line 85, in pandas._libs.tslibs.tzconversion.Localizer.__cinit__
  File "pandas/_libs/tslibs/timezones.pyx", line 306, in pandas._libs.tslibs.timezones.get_dst_info
AttributeError: 'NoneType' object has no attribute 'total_seconds'
Traceback (most recent call last):
  File "pandas/_libs/tslibs/tzconversion.pyx", line 85, in pandas._libs.tslibs.tzconversion.Localizer.__cinit__
  File "pandas/_libs/tslibs/timezones.pyx", line 306, in pandas._libs.tslibs.timezones.get_dst_info
AttributeError: 'NoneType' object has no attribute 'total_seconds'
Exception ignored in: 'pandas._libs.tslibs.conversion._localize_tso'
Traceback (most recent call last):
  File "pandas/_libs/tslibs/tzconversion.pyx", line 85, in pandas._libs.tslibs.tzconversion.Localizer.__cinit__
  File "pandas/_libs/tslibs/timezones.pyx", line 306, in pandas._libs.tslibs.timezones.get_dst_info
AttributeError: 'NoneType' object has no attribute 'total_seconds'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/core/frame.py", line 1063, in __repr__
    return self.to_string(**repr_params)
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/core/frame.py", line 1244, in to_string
    return fmt.DataFrameRenderer(formatter).to_string(
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1136, in to_string
    string = string_formatter.to_string()
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/string.py", line 30, in to_string
    text = self._get_string_representation()
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/string.py", line 45, in _get_string_representation
    strcols = self._get_strcols()
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/string.py", line 36, in _get_strcols
    strcols = self.fmt.get_strcols()
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 617, in get_strcols
    strcols = self._get_strcols_without_index()
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 883, in _get_strcols_without_index
    fmt_values = self.format_col(i)
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 897, in format_col
    return format_array(
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1328, in format_array
    return fmt_obj.get_result()
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1359, in get_result
    fmt_values = self._format_strings()
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1828, in _format_strings
    values = self.values.astype(object)
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 650, in astype
    return dtl.DatetimeLikeArrayMixin.astype(self, dtype, copy)
  File "/home/makos/.venv/lib/python3.8/site-packages/pandas/core/arrays/datetimelike.py", line 438, in astype
    converted = ints_to_pydatetime(
  File "pandas/_libs/tslibs/vectorized.pyx", line 135, in pandas._libs.tslibs.vectorized.ints_to_pydatetime
  File "pandas/_libs/tslibs/tzconversion.pyx", line 85, in pandas._libs.tslibs.tzconversion.Localizer.__cinit__
  File "pandas/_libs/tslibs/timezones.pyx", line 306, in pandas._libs.tslibs.timezones.get_dst_info
AttributeError: 'NoneType' object has no attribute 'total_seconds'
```

**Comment by erdewit** [comment]
This looks like a bug in Pandas in combination with ``backports.zoneinfo``. Python >= 3.9 has the zoneinfo module by default and should work with no issues. It certainly works with pandas 1.5.2 on Python 3.11.

**Comment by mmzx** [comment]
Thank you for your support and prompt reply! - Appreciated.
